apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: data
  labels:
    app: postgres
stringData:
  POSTGRES_DB: appdb
  POSTGRES_USER: appuser
  POSTGRES_PASSWORD: supersecretpassword