server:
  extraArgs:
    - '--insecure'
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hostname: argocd.${domain}
    extraTls:
      - hosts:
          - argocd.${domain}
        secretName: argocd-server-tls